---
title: "Visualise SOFUN"
author: "Beni Stocker"
date: "2/2/2021"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(rbeni)
```

## Read output

Annual

```{r}
nc_gpp <- read_nc_onefile("~/sofun/output_nc/global_FULL_MODIS-C006_MOD15A2_v3.3.2000.a.gpp.nc", varnam = "gpp")
nc_pet <- read_nc_onefile("~/sofun/output_nc/global_FULL_MODIS-C006_MOD15A2_v3.3.2000.a.pet.nc", varnam = "pet")
nc_alpha <- read_nc_onefile("~/sofun/output_nc/global_FULL_MODIS-C006_MOD15A2_v3.3.2000.a.alpha.nc", varnam = "alpha")
```

Daily: Take mean over daily values and read file.

```{r}
nc_wcont <- nc_timmean("~/sofun/output_nc/global_FULL_MODIS-C006_MOD15A2_v3.3.2000.d.wcont.nc")
nc_vpd <- nc_timmean("~/sofun/output_nc/global_FULL_MODIS-C006_MOD15A2_v3.3.2000.d.vpd.nc")
```

## Global maps

Annual

```{r}
plot_map3(nc_gpp, varnam = "gpp")
plot_map3(nc_pet, varnam = "pet")
plot_map3(nc_alpha, varnam = "alpha")
plot_map3(nc_wcont, varnam = "wcont")
plot_map3(nc_vpd, varnam = "vpd")
```

## Integrate globally

```{r}
df <- integrate_lonlat("~/sofun/output_nc/global_FULL_MODIS-C006_MOD15A2_v3.3.2000.a.gpp.nc", 
                       "~/sofun/output_nc/global_FULL_MODIS-C006_MOD15A2_v3.3.fland.nc",
                       varnam = "gpp")
```
